# Generated by Django 2.2.19 on 2022-02-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220110_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, null=True, verbose_name='Заголовок'),
        ),
    ]
