# Generated by Django 2.2.19 on 2022-02-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220215_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light-theme.css', 'Светлая'), ('dark-theme', 'Тёмная')], default='light-theme.css', max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='use_pop_article',
            field=models.BooleanField(default=True, verbose_name='Отображать популярные записи'),
        ),
    ]
